import { expect, test } from '@playwright/test'

test('studio push updates, draft preservation, duplicates, reconnect and account cleanup', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/realtime')
  const title = page.locator('input[name="title"]')
  await expect(title).toHaveValue('Original title')
  await expect(page.getByRole('button', { name: '内容变更会自动更新', exact: true })).toBeVisible()
  await title.fill('Unsaved draft')
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.state.video.title = 'Remote title'
    h.state.video.description = 'Remote description'
    h.state.video.muxTrackId = 'updated-track'
    h.lastEvent = h.send()
  })
  await expect(page.locator('textarea[name="description"]')).toHaveValue('Remote description')
  await expect(title).toHaveValue('Unsaved draft')
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.connections.at(-1).send(h.lastEvent)
    h.connections.at(-1).change('disconnected')
    h.state.video.description = 'Reconnected description'
    h.connections.at(-1).change('connected')
  })
  await expect(page.locator('textarea[name="description"]')).toHaveValue('Reconnected description')
  const polls = await page.evaluate(() => {
    // @ts-expect-error browser harness
    return window.realtimeTest.state.polls
  })
  await page.waitForTimeout(3000)
  expect(
    await page.evaluate(() => {
      // @ts-expect-error browser harness
      return window.realtimeTest.state.polls
    })
  ).toBe(polls)
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.state.deleted = true
    h.send('deletion.changed')
  })
  await expect(page.getByRole('alert')).toContainText('视频已删除')
  await expect(title).toHaveValue('Unsaved draft')
  await expect(page.getByRole('button', { name: '保存', exact: true })).toBeDisabled()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.state.deleted = false
    h.state.account = 'another-owner'
    h.show()
  })
  await expect(page.getByRole('button', { name: '内容变更会自动更新', exact: true })).toBeVisible()
  expect(
    await page.evaluate(() => {
      // @ts-expect-error browser harness
      const all = window.realtimeTest.connections
      return all.slice(0, -1).every((c: { closed: boolean }) => c.closed) && all.at(-1).channelName === 'studio:user:another-owner'
    })
  ).toBe(true)
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    window.realtimeTest.leave()
  })
  await expect(page.getByText('Left', { exact: true })).toBeVisible()
  expect(
    await page.evaluate(() => {
      // @ts-expect-error browser harness
      return window.realtimeTest.connections.every((c: { closed: boolean }) => c.closed)
    })
  ).toBe(true)
  expect(errors).toEqual([])
})

test('AI completion and deletion list arrive through events without polling', async ({ page }) => {
  await page.goto('/realtime')
  await expect(page.locator('input[name="title"]')).toHaveValue('Original title')
  await page.getByRole('button', { name: 'AI 生成标题', exact: true }).click()
  await expect(page.locator('input[name="title"]')).toBeDisabled()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    const job = Object.values(h.state.runs).at(-1) as { status: string; result: string }
    job.status = 'completed'
    job.result = 'Generated by push'
    h.state.video.title = job.result
    h.send('generation.changed', 'title')
  })
  await expect(page.locator('input[name="title"]')).toHaveValue('Generated by push')
  await expect(page.locator('input[name="title"]')).toBeEnabled()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.state.video.deletionRequestedAt = new Date()
    h.show(true)
  })
  await expect(page.getByText('正在删除')).toBeVisible()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.state.video.deletionError = 'failed'
    h.send('deletion.changed')
  })
  await expect(page.getByText('删除失败')).toBeVisible()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    const h = window.realtimeTest
    h.state.deleted = true
    h.send('deletion.changed')
  })
  await expect(page.getByText('Generated by push')).toHaveCount(0)
})

test('connection indicator stays quiet during reconnects and offers recovery after a sustained outage', async ({ page }) => {
  await page.goto('/realtime')
  const connected = page.getByRole('button', { name: '内容变更会自动更新', exact: true })
  const retry = page.getByRole('button', { name: '自动更新已暂停，点击重新连接', exact: true })
  await expect(connected).toBeVisible()
  await expect(page.getByRole('button', { name: '刷新状态', exact: true })).toHaveCount(0)
  await connected.focus()
  await expect(page.getByRole('tooltip')).toContainText('内容变更会自动更新')
  await page.clock.install()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    window.realtimeTest.connections.at(-1).change('disconnected')
  })
  await expect(connected).toHaveCount(0)
  await expect(retry).toHaveCount(0)
  await page.clock.runFor(5_000)
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    window.realtimeTest.connections.at(-1).change('connected')
  })
  await expect(connected).toBeVisible()
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    window.realtimeTest.connections.at(-1).change('disconnected')
  })
  await page.clock.runFor(9_000)
  await expect(retry).toHaveCount(0)
  await page.evaluate(() => {
    // @ts-expect-error browser harness
    window.realtimeTest.connections.at(-1).change('connecting')
  })
  await page.clock.runFor(1_100)
  await expect(retry).toBeVisible()
  await retry.focus()
  await page.keyboard.press('Enter')
  await expect(connected).toBeVisible()
  expect(
    await page.evaluate(() => {
      // @ts-expect-error browser harness
      const all = window.realtimeTest.connections
      return all.length === 2 && all[0].closed
    })
  ).toBe(true)
})
