import './globals.css'

import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Noto_Sans_SC } from 'next/font/google'

import { TRPCProvider } from '@/trpc/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const notoSansSC = Noto_Sans_SC({
  weight: ['400', '700'],
  display: 'swap',
  preload: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  console.log('hello')
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={notoSansSC.className}>
          <TRPCProvider>{children}</TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
