import './globals.css'

import { zhCN } from '@clerk/localizations'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Noto_Sans_SC } from 'next/font/google'

import { Toaster } from '@/components/ui/sonner'
import { TRPCProvider } from '@/trpc/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const notoSansSC = Noto_Sans_SC({
  weight: ['400', '700'],
  display: 'swap',
  preload: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={zhCN}>
      <html lang="en">
        <body className={notoSansSC.className}>
          <TRPCProvider>
            <Toaster />
            {children}
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
